version: "3.9"
services:
  # Database service
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: dodopayments
  # Application service
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://db_user:db_pass@db:5432/dodopayments
    depends_on:
      - db
volumes:
  db_data:
